#### GNS3 Server settings
gns3_url: "http://localhost"
gns3_project_name: tiny
gns3_lab_user: adsl@b
gns3_lab_pass: adsl@b123456
gns3_nodes_strategy: all

### Nodes attributes and specifications
gns3_nodes_spec:
    - name: pc-1
      template: "ads-lab-alpine"
    - name: pc-2
      template: "ads-lab-alpine"
    - name: netautomator
      template: "ads-lab-workstation"
    - name: logstash
      template: "ads-lab-logstash"
    - name: kibana
      template: "ads-lab-kibana"
    - name: elasticsearch
      template: "ads-lab-elasticsearch"
    - name: router-1
      template: "cisco-c3660"
    - name: nat
      template: "NAT"
    - name: switch-1
      template: "Ethernet switch"
    - name: switch-2
      template: "Ethernet switch"
    - name: switch-3
      template: "Ethernet switch"

### Links mapping
gns3_links_spec:
    - ["switch-1", "Ethernet0", "router-1", "FastEthernet0/0"]
    - ["switch-1", "Ethernet1", "elasticsearch", "eth0"]
    - ["switch-1", "Ethernet2", "kibana", "eth0"]
    - ["switch-1", "Ethernet3", "logstash", "eth0"]
    - ["switch-1", "Ethernet4", "netautomator", "eth0"]
    - ["netautomator", "eth1", "logstash", "eth1"]
    - ["router-1", "FastEthernet0/1", "switch-2", "Ethernet0"]
    - ["router-1", "FastEthernet2/0", "nat", "nat0"]
    - ["router-1", "FastEthernet1/0", "switch-3", "Ethernet0"]
    - ["switch-2", "Ethernet1", "pc-1", "eth0"]
    - ["switch-3", "Ethernet1", "pc-2", "eth0"]


### Boilerplate configuration settings
boilerplate:
    # `generate` or `deploy` the configuration
    config: "deploy"
    # Flag used when config is set to `deploy`. When `no` it will prompt the user for
    # confirmation, when set to `yes` it will wait the minuites set in `automated_push_delay`
    automated_push: "yes"
    automated_push_delay: 2

